app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/


Route::get('/',  'Auth\AuthController@getLogin');
Route::post('login', 'Auth\AuthController@postLogin');
Route::get('logout', 'Auth\AuthController@getLogout');
Route::controller('contrasena','Auth\PasswordController');

Route::get('principal',["middleware"=>"auth", function(){
    return view('principal');
}]  );


//
//Rutas para el gestor de los Maestros
//

Route::group(['prefix' => 'maestros/'], function () {
    Route::resource('modelosAeronaves', 'ModeloAeronaveController');
    Route::get('estadoPiloto', 'PilotoController@estadoPiloto');
    Route::resource('pilotos', 'PilotoController');
    Route::get('estadoPuerto', 'PuertoController@estadoPuerto');
    Route::resource('puertos', 'PuertoController');
    Route::resource('hangares', 'HangarController');
    Route::resource('aeronaves', 'AeronaveController');
});




Route::group(['prefix' => 'cobranza/{modulo}/'], function () {
    Route::get('main', 'CobranzaController@main');
    Route::get('getFacturasClientes', 'CobranzaController@getFacturasClientes');
    Route::resource('cobro', 'CobranzaController');
});

Route::group(['prefix' => 'facturacion/{modulo}/'], function () {
    Route::get('main', 'FacturaController@main');
    Route::resource('factura', 'FacturaController');
});

Route::get('estacionamiento/saveClient', 'EstacionamientoController@saveClient');

Route::get('estacionamiento/getClients', 'EstacionamientoController@getClients');

Route::resource('estacionamiento', 'EstacionamientoController');

Route::get('contrato/lote',"ContratoController@lote");
Route::post('contrato/lote',"ContratoController@loteStore");
Route::resource('contrato', 'ContratoController');




Route::group(['prefix' => 'administracion/'], function () {
    Route::get('usuario/estadoUser', 'UsuarioController@estadoUser');
    Route::resource('usuario', 'UsuarioController');


    Route::get('informacion', 'InformacionController@index');
    Route::get('informacion/update', 'InformacionController@update');
    Route::get('sincronizacion', function(){
        return view('administracion/sincronizacion');
    });
    Route::resource('modulo', 'ModuloController');
    Route::resource('cliente', 'ClienteController');
    Route::resource('concepto', 'ConceptoController');
    Route::get('roles/{roles}/users', 'RolesController@users');
    Route::post('roles/{roles}/users', 'RolesController@syncUsers');
    Route::resource('roles', 'RolesController');
});

app/Concepto.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Concepto extends Model {

    protected $guarded = array();

    public function modulo()
    {
        return $this->belongsTo('App\Modulo');
    }
    public function aeropuerto()
    {
        return $this->belongsTo('App\Aeropuerto');
    }
    public function facturadetalles()
    {
        return $this->hasMany('App\Facturadetalle');
    }
}

app/Factura.php
<?php namespace App;

use Illuminate\Database\Eloquent\Model;

class Factura extends Model {

    protected $guarded = array();

    public function detalles()
    {
        return $this->hasMany('App\Facturadetalle');
    }

    public function metadata()
    {
        return $this->hasOne('App\Facturametadata');
    }

    public function cliente()
    {
        return $this->belongsTo('App\Cliente');
    }

    public function cobros()
    {
        return $this->belongsToMany('App\Cobro')->withPivot('monto')-> withTimestamps();
    }


    public function getSubtotalNetoAttribute($value){
        return number_format($value,2);
    }
    public function getDescuentoTotalAttribute($value){
        return number_format($value,2);
    }
    public function getSubtotalAttribute($value){
        return number_format($value,2);
    }

    public function getIvaAttribute($value){
        return number_format($value,2);
    }
    public function getRecargoTotalAttribute($value){
        return number_format($value,2);
    }
    public function getTotalAttribute($value){
        return number_format($value,2);
    }
    public function setFechaAttribute($fecha)
    {
        $this->attributes['fecha']=\Carbon\Carbon::createFromFormat('d/m/Y', $fecha);
    }
    public function getFechaAttribute($fecha)
    {
        $carbon=\Carbon\Carbon::now();
        if(!is_null($fecha) && $fecha!="" )
            $carbon= \Carbon\Carbon::createFromFormat('Y-m-d', $fecha);
        return $carbon->format('d/m/Y');
    }
    public function setFechaVencimientoAttribute($fecha)
    {
        $this->attributes['fechaVencimiento']=\Carbon\Carbon::createFromFormat('d/m/Y', $fecha);
    }
    public function getFechaVencimientoAttribute($fecha)
    {
        $carbon=\Carbon\Carbon::now()->addMonth();
        if(!is_null($fecha) && $fecha!="" )
            $carbon= \Carbon\Carbon::createFromFormat('Y-m-d', $fecha);
        return $carbon->format('d/m/Y');
    }
}

resources/views/concepto/create.blade.php
@extends('app')
@section('content')
<ol class="breadcrumb">
  <li><a href="{{url('principal')}}">Inicio</a></li>
  <li><a href="{{action('ConceptoController@index')}}">Conceptos</a></li>
  <li><a class="active">Creación de concepto</a></li>
</ol>
         <div class="row" id="box-wrapper">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">

                  <div class="box-header">
                    <h3 class="box-title">Creación de concepto</h3>
                  </div><!-- /.box-header -->
                  <!-- form start -->
                    {!! Form::model($concepto, ["url" => "administracion/concepto", "method" => "POST", "class" => "form-horizontal"]) !!}
                        @include('concepto.partials.form', ["SubmitBtnText"=>"Crear", "disabled" =>""])
                    {!! Form::close() !!}
                </div><!-- /.box -->
              </div>
            </div>


@endsection

resources/views/concepto/edit.blade.php
@extends('app')
@section('content')
<ol class="breadcrumb">
  <li><a href="{{url('principal')}}">Inicio</a></li>
  <li><a href="{{action('ConceptoController@index')}}">Conceptos</a></li>
  <li><a class="active">Edición de concepto</a></li>
</ol>
         <div class="row" id="box-wrapper">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">

                  <div class="box-header">
                    <h3 class="box-title">Edición de concepto</h3>
                  </div><!-- /.box-header -->
                  <!-- form start -->
                    {!! Form::model($concepto, ['route' => ['administracion.concepto.update', $concepto->id], "method" => "PUT", "class" => "form-horizontal"]) !!}
                        @include('concepto.partials.form', ["SubmitBtnText"=>"Modificar", "disabled" =>""])
                    {!! Form::close() !!}
                </div><!-- /.box -->
              </div>
            </div>


@endsection

resources/views/concepto/index.blade.php
@extends('app')


@section('content')
<ol class="breadcrumb">
  <li><a href="{{url('principal')}}">Inicio</a></li>
  <li><a class="active">Conceptos</a></li>
</ol>
             <div class="row" id="box-wrapper">
              <!-- left column -->
              <div class="col-md-12">
                <!-- general form elements -->
                <div class="box box-primary">
                  <div class="box-header">
                    <h3 class="box-title">Gestión de Conceptos</h3>
{{--        no deberia poderse agregar conceptos por este sistema, solo sincronizacion

        <div class="box-tools pull-right">
                         <a class="btn btn-primary" href="{{action("ConceptoController@create")}}"><span class="glyphicon glyphicon-plus-sign"></span> Agregar un concepto</a>
                        </div>--}}
                  </div><!-- /.box-header -->
                  <!-- form start -->

                  <div class="box-body"  id="container">
                    <div class="row">
                      <div class="col-xs-12">
                        <ul class="list-group">
                        @foreach($conceptos as $concepto)
                            <li class="list-group-item modulos-li" style="margin-bottom:-3px" title="{{$concepto->descripcion}}">
                                <div class="row">
                                    <div class="col-xs-12 shrinkable" style="cursor:pointer; padding-top:15px; padding-bottom:15px; margin-top:-15px; margin-bottom:-15px" data-min="10" data-max="12" data-target=".control-btns" data-is="max">
                                        {{$concepto->nompre}}
                                        <span class="pull-right">IVA {{$concepto->iva}} %</span>
                                    </div>

                                    <div class="control-btns" style="display:none">
                                    <div  data-toggle="modal" data-target="#show-modal" data-id="{{$concepto->id}}" class="col-xs-1 text-center bg-light-blue info-modulo-btn" style="padding:15px; margin:-14px auto;cursor:pointer" >
                                        <span  class="glyphicon glyphicon-eye-open"></span>
                                    </div>
                                    <a href="{{action("ConceptoController@edit", [$concepto->id])}}" >
                                    <div class="col-xs-1 text-center bg-yellow" style="padding:15px; margin:-14px auto;">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </div>
                                    </a>
{{--       no deberia poder eliminar conceptos por el sistema

  <div data-id="{{$concepto->id}}" data-nombre="{{$concepto->nompre}}" class="col-xs-1 text-center bg-red delete-concepto-btn" style="padding:15px; margin:-14px auto;cursor:pointer" >
                                        <span class="glyphicon glyphicon-trash"></span>
                                    </div>--}}
                                    </div>
                                </div>
                            </li>
                        @endforeach
                        </ul>
                      </div>
                    </div>
                  </div><!-- /.box-body -->
                </div><!-- /.box -->
              </div>
            </div>
        <!-- Modal -->
        <div class="modal fade" id="show-modal" tabindex="-1" role="dialog" aria-labelledby="cliente-show-modal">
            <div class="modal-dialog modal-lg" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                        <h4 class="modal-title" id="myModalLabel">Concepto</h4>
                    </div>
                    <div class="modal-body">
                    </div>
                    <div class="modal-footer">
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Cerrar</button>
                    </div>
                </div>
            </div>
        </div>
@endsection


@section('script')

<script>
$(document).ready(function(){

    $('.shrinkable').click(function(){
        var data=$(this).data();
        var li=$(this).closest('li');
        switch(data.is){
            case "max":
                $(this).switchClass("col-xs-"+data.max,"col-xs-"+data.min,function(){$(li).find(data.target).show();} );
                $(this).data('is','min');
            break;

            case "min":
                $(li).find(data.target).hide();
                $(this).switchClass("col-xs-"+data.min,"col-xs-"+data.max );
                $(this).data('is','max');
            break;
        }
    })

    $('.delete-concepto-btn').click(function(){
        var li=$(this).closest('li');
        var data=$(this).data();
        var url="{{url('administracion/concepto')}}/"+data.id;
        alertify.confirm("Desea eliminar el concepto de "+data.nombre+"?. Los conceptos asociados seran liberados", function (e) {
    if (e) {
        $.
        ajax({url: url,
              method:"DELETE"})
        .done(function(response, status, responseObject){
            try{
                var obj= JSON.parse(responseObject.responseText);
                if(obj.success==1){
                    $(li).remove();
                    alertify.success(obj.text);
                }
            }catch(e){
            console.log(e);
            alertify.error("Error en el servidor");
            }
        })
    }
        });

    })


$('#show-modal').on('show.bs.modal', function (e) {
  var id=$(e.relatedTarget).data("id");
  $('#show-modal .modal-body').html("Cargando...")
                              .load("{{url('administracion/concepto')}}/"+id, function(){
                              $('.modal-backdrop').css('height',"1000px")
                              });
})

})


</script>

@endsection